services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: mafit-app
    restart: unless-stopped
    working_dir: /var/www/mafit
    volumes:
      - ./:/var/www/mafit
    environment:
      APP_ENV: production
      APP_DEBUG: false
      FILESYSTEM_DISK: google
    # Usar red "host" para acceder a la base de datos local del VPS (127.0.0.1:3306)
    network_mode: host

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/mafit
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # Usar red "host" para exponer puerto 80 directamente
    network_mode: host
    depends_on:
      - app
